__use_yte__ = true

# CONFIG FOR DIET INTERVENTION STUDY
##############################################################################

##############################################################################
analyst: "Jack OConnor"
repository: "HIV-Diet-Intervention"
scripts_dir: "scripts"
qiime_data_dir: "data/QIIME_Files"


