# CONFIG FOR DIET INTERVENTION STUDY
##############################################################################

##############################################################################
analyst: "Jack OConnor"
repository: "HIV-Diet-Intervention"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Bash script
        run: bash path/to/your_bash_script.sh
